// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC71FGZ6ruI2T1kVElNO259HhY9D5iTjk',
    appId: '1:986950434792:web:f08d81d1ad2fffe35d2e5d',
    messagingSenderId: '986950434792',
    projectId: 'presencejor',
    authDomain: 'presencejor.firebaseapp.com',
    storageBucket: 'presencejor.appspot.com',
    measurementId: 'G-ZY6ZX31Q4V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxB1P3DpWoOiISwcHRZE_xRikLF0WTX8c',
    appId: '1:986950434792:ios:9c163189951077525d2e5d',
    messagingSenderId: '986950434792',
    projectId: 'presencejor',
    storageBucket: 'presencejor.appspot.com',
    iosClientId: '986950434792-13cnj6p68ll5kvq4gavcl24js6ls70gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceJor',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxB1P3DpWoOiISwcHRZE_xRikLF0WTX8c',
    appId: '1:986950434792:ios:9c163189951077525d2e5d',
    messagingSenderId: '986950434792',
    projectId: 'presencejor',
    storageBucket: 'presencejor.appspot.com',
    iosClientId: '986950434792-13cnj6p68ll5kvq4gavcl24js6ls70gt.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceJor',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVrQq8rlpksWNb9Ejgy96Ajj0TxnPB4VA',
    appId: '1:986950434792:android:19dc94af8e15cf555d2e5d',
    messagingSenderId: '986950434792',
    projectId: 'presencejor',
    storageBucket: 'presencejor.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC71FGZ6ruI2T1kVElNO259HhY9D5iTjk',
    appId: '1:986950434792:web:1d05c5a9c9a0de7e5d2e5d',
    messagingSenderId: '986950434792',
    projectId: 'presencejor',
    authDomain: 'presencejor.firebaseapp.com',
    storageBucket: 'presencejor.appspot.com',
    measurementId: 'G-PF594MNHLV',
  );

}